
package nik_lab4;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;


public class NewJFrame extends javax.swing.JFrame {

    public NewJFrame() {

        initComponents();
        this.getContentPane().setBackground(java.awt.Color.lightGray);
        jButton1.setText("Выполнить");
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String s  = textArea1.getText();
                s=s.replace(" ", " ");
                String[] splited = s.split(" ");

                Arrays.sort(splited);
                System.out.println(Arrays.toString(splited));

                int max = 0;
                int count= 1;
                String word = splited[0];
                String curr = splited[0];

                int [] counters = new int[splited.length];
                String [] words = new String[splited.length];
                int cc = 0;
                for(int i = 1; i<splited.length; i++){
                    if(splited[i].equals(curr)){
                        count++;
                    }
                    else{

                        counters[cc] = count;
                        words[cc] = splited[i-1];
                        cc++;
                        count =1;
                        curr = splited[i];
                    }
                    if(max<count){
                        max = count;
                        word = splited[i];
                    }
                }
                String output = "Максимальное повторяющееся слово =" + word + " x " + max+"\n";
                for (int i = 0; i < cc; i++) {
                    output += words[i]+" x "+counters[i]+"\n";
                }
                textArea2.setText(output);
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        textArea2 = new java.awt.TextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        textArea1.setBackground(new java.awt.Color(204, 255, 255));
        textArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textArea1.setText("Введите текст:");
        getContentPane().add(textArea1);
        textArea1.setBounds(30, 90, 420, 360);

        textArea2.setBackground(new java.awt.Color(153, 255, 102));
        textArea2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(textArea2);
        textArea2.setBounds(570, 90, 410, 360);

        jButton1.setText("Выполнить");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 180, 100, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nik_lab4/variant.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 20, 570, 50);

        setSize(new java.awt.Dimension(1007, 499));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private java.awt.TextArea textArea1;
    private java.awt.TextArea textArea2;
    // End of variables declaration//GEN-END:variables
}
